services:
  - type: web
    name: moe-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
