import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import AuthProvider from "@/components/providers/public-service/AuthProvider";
import DebugSlices from "@/components/ui/DebugSlices";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = { 
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased satoshi-font`}
            >
                <NextTopLoader
                    color="#047857"
                    showSpinner={false}
                />
                <Toaster
                    position="top-center"
                    expand={true}
                    richColors
                    toastOptions={{
                        style: {
                            padding: '16px 24px',
                            fontSize: '12px',
                            minHeight: '60px',
                        },
                        className: 'text-base',
                    }}
                />
                <StoreProvider>
                    <AuthProvider>{children}</AuthProvider>
                    <DebugSlices />
                </StoreProvider>
            </body>
        </html>
    );
}
